= 処理フロー

== 1. 日本版コアインボイス ゲートウェイ

.Invoice2csv.java & CSV2invoice.java
// [mermaid]
// ----
// classDiagram
//     class 日本版コアインボイス{TidyDataCSV_xBRL-CSV}

//     class Invoice2csv{javaプログラム}
//     class Csv2invoice{javaプログラム}

//     class UBLinvoice {JP-PINT}
//     class CIIinvoice {中小企業共通EDI}

//     UBLinvoice --|> Invoice2csv
//     CIIinvoice --|> Invoice2csv

//     Invoice2csv --|> 日本版コアインボイス
//     日本版コアインボイス --|> Csv2invoice

//     Csv2invoice --|> UBLinvoice
//     Csv2invoice --|> CIIinvoice
// ----
.Invoice2csv.java & CSV2invoice.java
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAwrPpS5_NWfO8s-Nx0-bHTYseNy153Lz5cfMcEKNpZ3VIZkqlS2JJonNwWHyFU5CPLpBRy4Wk3zOvLD8zOdUoubisOiuxLPFx8_THzWsfN2143LzycfOCWiSlzsVlRpkQ5diVIqkNdfKBKlWo9grQDfD0C0ExytMTLv1kx9qnG_qf7Gl8tnTt09aNLxtmubp4Qg1DMkZXt8YO2bVgeSRzMOTBCpAEICrwhxdYD34lEGOQwgJiEZIARAXC6djlEU4HALveyG4=[Invoice2csv.java &amp; CSV2invoice.java]

https://www.wuwei.space/core-japan/[日本版コアインボイス変換サービス]

== 2. 検索専用ブラウザ

XBRL-GLから変換したinstances.csv（TidyData形式CSV　xBRL-CSV）を検索専用ブラウザ用のCSVに変換し、ブラウザで表示する。

XBRL-GL 構文バインディング xBRL_GL_binding.csv (XBRL_GL2csv.javaで使用)

.horizontal_ledger.py & general_ledger.py
// [mermaid]
// ----
// classDiagram
//     class XBRLGL {XBRL}
//     class XBRL_GL2csv {javaプログラム}
//     class xBRL_GL_binding {構文バインディング}

//     class instances{TidyDataCSV_xBRL-CSV}

//     class horizontal_ledger{pythonプログラム}
//     class general_ledger{pythonプログラム}

//     class horizontal_ledgerCSV{TidyDataCSV_xBRL-CSV}
//     class TrialBalance {共通CSV}
//     class GeneralLedger {共通CSV}

//     XBRLGL --|> XBRL_GL2csv
//     xBRL_GL_binding --|> XBRL_GL2csv
//     XBRL_GL2csv --|> instances

//     instances --|> horizontal_ledger
//     horizontal_ledger --|> horizontal_ledgerCSV

//     horizontal_ledgerCSV --|> general_ledger
//     general_ledger --|> TrialBalance
//     general_ledger --|> GeneralLedger
// ----
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAQoRTkI-7j0I1iK5FE4939zFKLi5TqM5KLEt83Dz9cfPax00bHjevfNy8AFltBURtfFJmXkpmXrpC9bPl3c-mtT9unvC4acnj5s2Pm9sfNy0GMZo21HIhaczMKy5JzEtOLa4OyUypdEksSXQODosHGacLZKAozcgvyqzKzytJzInPSU1JTy2qLqgsycjPw-Os9NS81CKC6vHZAXQEDpchNIUUZSbmOCXmgPyhUP20dePLhlloStwhDvEBm4miBqwIGgW6ujV2yMEOlkMPWqyKkOMKrAAerhAL4FyILIY3wYowRHEoBrqbC7sGoAxED2rAgxWjCkGUIYccTkUoYQcAvNwHHQ==[horizontal_ledger.py &amp; general_ledger.py]

https://www.wuwei.space/core-japan/journal_entry/[検索専用ブラウザ]

== 3. 会計パッケージのCSVとTidyData形式CSVの相互変換

EPSONから提供されるCSVファイルを対象に相互変換する。

論理モデルバインディング EPSON_binding.csv

.csv2tidy.py & tidy2csv.py
// [mermaid]
// ----
// classDiagram
//     class EPSON_binding {論理モデルバインディングCSV}

//     class csv2tidy {pythonプログラム}
//     class tidy2csv {pythonプログラム}

//     class 北海道産業_tidy {TidyDataCSV_xBRL-CSV}
//     class 北海道産業 {EPSON形式CSV}

//     北海道産業 --|> csv2tidy
//     EPSON_binding --|> csv2tidy
//     csv2tidy --|> 北海道産業_tidy

//     北海道産業_tidy --|> tidy2csv
//     EPSON_binding --|> tidy2csv
//     tidy2csv --|> 北海道産業
// ----
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAgmtAsL9ffFJmXkpmXrpC9YvV055PaHvcvOhxc_vj5tWPmyc8blryuHkziNu0GMRo2uAcHFbLhWREcnGZUUlmSqVCdUFlSUZ-3uPm6Y-b1wIVPm5e-bh5QS2SUpAyI6B6nEqR1D7tmf5s6_aXjZOfT1n8bOnaeIgVIUDSJbEkEeiI-AqnIB9dsGtw6lKoBnvw6d5FT_f0IxyOrkpXt8YO7g-wCtRwwZSHexoshc2tWG2KR-iBhQUu61Dk4QGHzToAieHSdg==[csv2tidy.py &amp; tidy2csv.py]

== Marmaid

VS CodeのAscii DocでMermaid Markdown Syntax Highlighting機能拡張を使用。

Mermaidについては、 +
https://mermaid.js.org/syntax/classDiagram.html

== 残作業(2023-05-17)

. 2 と 3 では、使用したバインディング定義ファイルの前提としている論理階層モデルが異なる。　2 の定義を更新して再確認する。

. 検索専用ブラウザに消費税項目を追加する。

. EPSONからのCSVを検索専用ブラウザで表示可能とする。