= 処理フロー

== 1. 日本版コアインボイス ゲートウェイ

.Invoice2csv.java & CSV2invoice.java
// [mermaid]
// ----
// classDiagram
//     class 日本版コアインボイス{TidyDataCSV_xBRL-CSV}

//     class Invoice2csv{javaプログラム}
//     class Csv2invoice{javaプログラム}

//     class UBLinvoice {JP-PINT}
//     class CIIinvoice {中小企業共通EDI}

//     UBLinvoice --|> Invoice2csv
//     CIIinvoice --|> Invoice2csv

//     Invoice2csv --|> 日本版コアインボイス
//     日本版コアインボイス --|> Csv2invoice

//     Csv2invoice --|> UBLinvoice
//     Csv2invoice --|> CIIinvoice
// ----
.Invoice2csv.java & CSV2invoice.java
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAwrPpS5_NWfO8s-Nx0-bHTYseNy153Lz5cfMcEKNpZ3VIZkqlS2JJonNwWHyFU5CPLpBRy4Wk3zOvLD8zOdUoubisOiuxLPFx8_THzWsfN2143LzycfOCWiSlzsVlRpkQ5diVIqkNdfKBKlWo9grQDfD0C0ExytMTLv1kx9qnG_qf7Gl8tnTt09aNLxtmubp4Qg1DMkZXt8YO2bVgeSRzMOTBCpAEICrwhxdYD34lEGOQwgJiEZIARAXC6djlEU4HALveyG4=[Invoice2csv.java &amp; CSV2invoice.java]

https://www.wuwei.space/core-japan/[日本版コアインボイス変換サービス]

== 2. 検索専用ブラウザ

XBRL-GLから変換したinstances.csv（TidyData形式CSV　xBRL-CSV）を検索専用ブラウザ用のCSVに変換し、ブラウザで表示する。

.horizontal_ledger.py & general_ledger.py
// [mermaid]
// ----
// classDiagram
//     class XBRLGL {XBRL}
//     class XBRL_GL2csv {javaプログラム}
//     class xBRL_GL_binding {構文バインディング}

//     class instances{TidyDataCSV_xBRL-CSV}

//     class horizontal_ledger{pythonプログラム}
//     class general_ledger{pythonプログラム}

//     class horizontal_ledgerCSV{TidyDataCSV_xBRL-CSV}
//     class TrialBalance {共通CSV}
//     class GeneralLedger {共通CSV}

//     XBRLGL --|> XBRL_GL2csv
//     xBRL_GL_binding --|> XBRL_GL2csv
//     XBRL_GL2csv --|> instances

//     instances --|> horizontal_ledger
//     horizontal_ledger --|> horizontal_ledgerCSV

//     horizontal_ledgerCSV --|> general_ledger
//     general_ledger --|> TrialBalance
//     general_ledger --|> GeneralLedger
// ----
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAQoRTkI-7j0I1iK5FE4939zFKLi5TqM5KLEt83Dz9cfPax00bHjevfNy8AFltBURtfFJmXkpmXrpC9bPl3c-mtT9unvC4acnj5s2Pm9sfNy0GMZo21HIhaczMKy5JzEtOLa4OyUypdEksSXQODosHGacLZKAozcgvyqzKzytJzInPSU1JTy2qLqgsycjPw-Os9NS81CKC6vHZAXQEDpchNIUUZSbmOCXmgPyhUP20dePLhlloStwhDvEBm4miBqwIGgW6ujV2yMEOlkMPWqyKkOMKrAAerhAL4FyILIY3wYowRHEoBrqbC7sGoAxED2rAgxWjCkGUIYccTkUoYQcAvNwHHQ==[horizontal_ledger.py &amp; general_ledger.py]

XBRL-GL 構文バインディング xBRL_GL_binding.csv (XBRL_GL2csv.javaで使用)

[%header,format=csv]
|===
semSort,id,card,level,businessTerm,desc,defaultValue,dataType,syntaxID,businessTerm_en,businessTerm_ja,desc_ja,synSort,xPath,occur
1000,GL02,--,0,GL,"Contains all of the journal entry details for each transaction (e.g. associated journal entry ID, associated account number, debits or credits associated with the journal entry line). This table should be at the journal entry line level.",,,,,,,1,/xbrli:group,--
1010,GL02-01,1..1,1,Journal ID,Unique identifier for each journal entry.Typically auto-generated by the system.,,Identifier,,,,,4,/xbrli:group/gl-cor:accountingEntries/gl-cor:documentInfo/gl-cor:uniqueID,1..1
1090,GL02-GL64,0..1,1,Specified GL Source,,,,,,,,26,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader,0..1
1100,GL64-01,1..1,2,Source Code,"Code for the source from which the journal entry originated.EXAMPLE   Sales journal, cash receipts journal, general journal, payroll journal, accountant manual entry, spreadsheet.Shall match the Source_Code [SrcCd] in the GL_Source [GlSrc] table.",,Identifier,,,,,28,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:sourceJournalID,1..1
1110,GL64-02,0..1,2,Source Description,Description of the source system.,,Text,,,,,5,/xbrli:group/gl-cor:accountingEntries/gl-cor:documentInfo/gl-bus:sourceApplication,0..1
1120,GL64-03,0..1,2,ERP Subledger Module,"Description of the subledger or ERP module from which the journal entry originated.This should tie back to a system or significant accounting process. In some instances, it can be represented by the source system.",,Text,,,,,29,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-bus:sourceJournalDescription,0..1
1130,GL64-04,0..1,2,System Manual Identifier,"Indicates whether the journal entry is system-generated or manually-entered.EXAMPLE   S is system-generated, M is manually-entered.",,Identifier,,,,,27,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-bus:entryOrigin,0..1
1140,GL02-GL57,0..1,2,Specified Created,Information about the data that was created into the system.,,,,,,,24,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader,0..1
1150,GL57-01,0..1,3,Created User ID,The unique identifier for the person who did the activity. Typically auto-generated by the system. Shall match the User_ID [UserId] in the BAS_User [BasUser] table.,,,,,,,8,/xbrli:group/gl-cor:accountingEntries/gl-cor:documentInfo/gl-bus:creator,0..1
1160,GL57-02,0..1,3,Created Date,"The date of activity. This should be a system generated date (rather than user-created date), when possible. This is sometimes referred to as the creation date.",,Date,,,,,25,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:enteredDate,0..1
1240,GL02-GL55,1..n,1,Specified GL Details,,,,,,,,32,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail,1..n
1270,GL55-03,0..1,2,Journal Entry Type Code,Code for the journal entry type.Shall match the JE_Type_Code [JeTypCd] in the BAS_Journal_Entry_Type [BasJrnEntryTyp] table.,,,,,,,36,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:account/gl-cor:accountType,0..1
1280,GL55-04,0..1,2,Journal Entry Line Description,Description of the individual line within the journal entry.,,Text,,,,,55,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:detailComment,0..1
1290,GL55-05,0..1,2,Credit Debit Indicator,"Indicates whether the amount is a credit or a debit.EXAMPLE   C is credit, D is debit.",,Code,,,,,41,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:debitCreditCode,0..1
1430,GL55-GL63,0..1,2,Specified Chart Of Accounts,,,,,,,,33,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:account,0..1
1440,GL63-01,1..1,3,GL Account Number,Number of the GL account.Shall match the GL_Account_Number [GlAcntNr] used in the AS_Chart_Of_Accounts table.,,Identifier,,,,,34,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:account/gl-cor:accountMainID,1..1
1450,GL63-02,0..1,3,GL Account Name,Name of the GL account.,,Text,,,,,35,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:account/gl-cor:accountMainDescription,0..1
1460,GL63-03,0..1,3,Financial Statement Caption,"Financial statement caption that represents a related group of accounts.EXAMPLE   Cash and cash equivalents, AP, cost of sales.The caption can be at the trial balance level.",,Text,,,,,54,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:xbrlInfo/gl-cor:xbrlElement,0..1
1470,GL55-GL56,0..1,2,Specified Amount,"Related amount expressed in functional, transaction, reporting and local currency.",,,,,,,42,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail,0..1
1480,GL56-01,0..1,3,Functional Amount,Amount recorded in the functional or group currency.,,Monetary Amount,,,,,43,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:amount,0..1
1490,GL56-02,0..1,3,Functional Currency Code,Code of the functional or group currency (in accordance with ISO 4217).Shall match the Currency_Code [CurCd] in the BAS_Currency [BasCur] table.,,,,,,,44,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-muc:amountCurrency,0..1
1560,GL55-GL69,0..1,2,Specified Posted,Information about the data that was posted.,,,,,,,45,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail,0..1
1580,GL69-02,0..1,3,Posted Date,"The date of activity. This should be a system generated date (rather than user-created date), when possible. This is sometimes referred to as the creation date.",,Date,,,,,46,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:postingDate,0..1
1590,GL55-GL60,0..n,2,Specified Account Segment,Contains associated Account Segment information.,,,,,,,37,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:account/gl-cor:accountSub,0..n
1600,GL60-01,0..1,3,Account Segment Number,Sequence number of the associated Account Segment. Must match Account_Segment_Number [AcntSgNr] in GL_Account_Segment [GlAcntSg] in relation to the GL_Account_Number [GlAcntNr] concerned.,,Code,,,,,40,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:account/gl-cor:accountSub/gl-cor:accountSubType,0..1
1610,GL60-02,0..1,3,Account Segment Code,Account Segment Code.,,Text,,,,,39,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:account/gl-cor:accountSub/gl-cor:accountSubID,0..1
1620,GL60-03,0..1,3,Account Segment Name,,,Text,,,,,38,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:account/gl-cor:accountSub/gl-cor:accountSubDescription,0..1
1630,GL55-GL61,0..n,2,Specified Business Segment,Contains associated Business Segment information.,,,,,,,47,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:identifierReference,0..n
1640,GL61-01,0..1,3,Business Segment Sequence Number,Number or text to keep the Business Segments in a predefined order.,,Code,,,,,50,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:identifierReference/gl-cor:identifierType,0..1
1650,GL61-02,0..1,3,Business Segment Code,Contains a code to identify the associated business segment. Must match the Business_Segment_Code [BusSgCd] in BAS_Business_Segment [BasBusSg].,,,,,,,48,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:identifierReference/gl-cor:identifierCode,0..1
1660,GL61-03,0..1,3,Organization Type Name,"Indicates the name of the organization type (e.g. department, cost centre).",,Text,,,,,49,/xbrli:group/gl-cor:accountingEntries/gl-cor:entryHeader/gl-cor:entryDetail/gl-cor:identifierReference/gl-cor:identifierDescription,0..1
|===

https://www.wuwei.space/core-japan/journal_entry/[検索専用ブラウザ]

== 3. 会計パッケージのCSVとTidyData形式CSVの相互変換

EPSONから提供されるCSVファイルを対象に相互変換する。

.csv2tidy.py & tidy2csv.py
// [mermaid]
// ----
// classDiagram
//     class EPSON_binding {論理モデルバインディングCSV}

//     class csv2tidy {pythonプログラム}
//     class tidy2csv {pythonプログラム}

//     class 北海道産業_tidy {TidyDataCSV_xBRL-CSV}
//     class 北海道産業 {EPSON形式CSV}

//     北海道産業 --|> csv2tidy
//     EPSON_binding --|> csv2tidy
//     csv2tidy --|> 北海道産業_tidy

//     北海道産業_tidy --|> tidy2csv
//     EPSON_binding --|> tidy2csv
//     tidy2csv --|> 北海道産業
// ----
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAgmtAsL9ffFJmXkpmXrpC9YvV055PaHvcvOhxc_vj5tWPmyc8blryuHkziNu0GMRo2uAcHFbLhWREcnGZUUlmSqVCdUFlSUZ-3uPm6Y-b1wIVPm5e-bh5QS2SUpAyI6B6nEqR1D7tmf5s6_aXjZOfT1n8bOnaeIgVIUDSJbEkEeiI-AqnIB9dsGtw6lKoBnvw6d5FT_f0IxyOrkpXt8YO7g-wCtRwwZSHexoshc2tWG2KR-iBhQUu61Dk4QGHzToAieHSdg==[csv2tidy.py &amp; tidy2csv.py]

論理モデルバインディング EPSON_binding.csv

[cols="^1,4,^1,^3,^1,12,^1",%header,format=csv]
|===
column,name,card,Representation,semSort,semPath,fixedValue
-,seq,,Identifier,1010,GL02-01,
A,月種別,,,,,0
B,種類,,,,,0
C,形式,0..1,Document Reference,1240,GL55-03,
D,作成方法,,,,,0
E,付箋,,,,,0
F,伝票日付,0..1,Date,1230,GL55-02,
G,伝票番号,0..1,Code,1020,GL02-02,
H,伝票摘要,0..1,Text,1030,GL02-03,
I,枝番,0..1,Code,1220,GL55-01,
J,借方部門,0..1,Document Reference,1490,GL02-GL55[GL55-05=借方]/GL55-GL61[GL61-01=部門]/GL60-02,
K,借方部門名,0..1,Text,1500,GL02-GL55[GL55-05=借方]/GL55-GL61[GL61-01=部門]/GL60-03,
L,借方科目,1..1,Identifier,1320,GL02-GL55[GL55-05=借方]/GL55-GL63/GL63-01,
M,借方科目名,0..1,Text,1330,GL02-GL55[GL55-05=借方]/GL55-GL63/GL63-02,
N,借方補助,0..1,Text,1390,GL02-GL55[GL55-05=借方]/GL55-GL60[GL60-01=補助科目]/GL60-02,
O,借方補助科目名,0..1,Text,1400,GL02-GL55[GL55-05=借方]/GL55-GL60[GL60-01=補助科目]/GL60-03,
P,借方金額,1..1,Monetary Amount,1350,GL02-GL55[GL55-05=借方]/GL55-GL56/GL56-01,
Q,借方消費税コード,0..1,Code,1520,GL02-GL55[GL55-05=借方]/GL55-GL68[GL68-04=消費税]/GL68-01,
R,借方消費税業種,0..1,Text,1430,GL02-GL55[GL55-05=借方]/GL55-GL60[GL60-01=業種]/GL60-02,
S,借方消費税税率,0..1,Percentage,1530,GL02-GL55[GL55-05=借方]/GL55-GL68[GL68-04=消費税]/GL68-02,
T,借方資金区分,0..1,Text,1460,GL02-GL55[GL55-05=借方]/GL55-GL60[GL60-01=資金区分]/GL60-02,
U,借方任意項目１,,,,,
V,借方任意項目２,,,,,
W,貸方部門,0..1,0,1730,GL02-GL55[GL55-05=貸方]/GL55-GL61[GL61-01=部門]/GL60-02,
X,貸方部門名,0..1,Text,1740,GL02-GL55[GL55-05=貸方]/GL55-GL61[GL61-01=部門]/GL60-03,
Y,貸方科目,1..1,Identifier,1560,GL02-GL55[GL55-05=貸方]/GL55-GL63/GL63-01,
Z,貸方科目名,0..1,Text,1570,GL02-GL55[GL55-05=貸方]/GL55-GL63/GL63-02,
AA,貸方補助,0..1,Text,1630,GL02-GL55[GL55-05=貸方]/GL55-GL60[GL60-01=補助科目]/GL60-02,
AB,貸方補助科目名,0..1,Text,1640,GL02-GL55[GL55-05=貸方]/GL55-GL60[GL60-01=補助科目]/GL60-03,
AC,貸方金額,1..1,Monetary Amount,1590,GL02-GL55[GL55-05=貸方]/GL55-GL56/GL56-01,
AD,貸方消費税コード,0..1,Code,1760,GL02-GL55[GL55-05=貸方]/GL55-GL68[GL68-04=消費税]/GL68-01,
AE,貸方消費税業種,0..1,Text,1670,GL02-GL55[GL55-05=貸方]/GL55-GL60[GL60-01=業種]/GL60-02,
AF,貸方消費税税率,0..1,Percentage,1770,GL02-GL55[GL55-05=貸方]/GL55-GL68[GL68-04=消費税]/GL68-02,
AG,貸方資金区分,0..1,Text,1700,GL02-GL55[GL55-05=貸方]/GL55-GL60[GL60-01=資金区分]/GL60-02,
AH,貸方任意項目１,,,,,
AI,貸方任意項目２,,,,,
AJ,摘要,0..1,Text,1250,GL55-04,
AK,期日,0..1,Date,1290,GL55-08,
AL,証番号,0..1,Code,1270,GL55-06,
AM,入力ユーザ,0..1,Identifier,1150,GL57-01,
AN,入力マシン,0..1,Document Reference,1130,GL64-04,
AO,入力アプリ,0..1,Text,1120,GL64-03,
AP,入力会社,0..1,Text,1110,GL64-02,
AQ,入力日付,0..1,Date,1160,GL57-02,
|===

== Marmaid

VS CodeのAscii DocでMermaid Markdown Syntax Highlighting機能拡張を使用。

Mermaidについては、 +
https://mermaid.js.org/syntax/classDiagram.html

== 残作業(2023-05-17)

. 検索専用ブラウザに消費税項目を追加する。

. EPSONからのCSVを検索専用ブラウザで表示可能とする。

. XBRL-GLから変換したxBRL-CSVに消費税項目を固定値として定義し、検索専用ブラウザに表示する。

. XBRL-GLから変換したxBRL-CSVをEPSONのCSVに変換する。