= 処理フロー

== 日本版コアインボイス ゲートウェイ

.Invoice2csv.java & CSV2invoice.java
// [mermaid]
// ----
// classDiagram
//     class 日本版コアインボイス{TidyDataCSV_xBRL-CSV}
//     class XBRLGL{XBRL}

//     class Invoice2csv{javaプログラム}
//     class Csv2invoice{javaプログラム}

//     class UBLinvoice {JP-PINT}
//     class CIIinvoice {中小企業共通EDI}

//     UBLinvoice --|> Invoice2csv
//     CIIinvoice --|> Invoice2csv
//     XBRLGL --|> Invoice2csv

//     Invoice2csv --|> 日本版コアインボイス
//     日本版コアインボイス --|> Csv2invoice

//     Csv2invoice --|> UBLinvoice
//     Csv2invoice --|> CIIinvoice
// ----
.Invoice2csv.java & CSV2invoice.java
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAwrPpS5_NWfO8s-Nx0-bHTYseNy153Lz5cfMcEKNpZ3VIZkqlS2JJonNwWHyFU5CPLpBRi6Q9Aijm7lMNomq5kMQ988ryM5NTjZKLy6qzEssSHzdPf9y89nHThsfNKx83L0A2wrm4zCgTohy7UiS1oU4-UKUK1V4BugGefiEoRnl6wqWf7Fj7dEP_kz2Nz5aufdq68WXDLFcXT6hhSMbo6tbYIbsWLI9kDlZ5iK8x5cCSSAIQFfiDGKwHvxKIMUjhBLEISQCiAuEt7PIIbwEA_13XHQ==[Invoice2csv.java &amp; CSV2invoice.java]

== 検索専用ブラウザ

XBRL-GLから変換したinstances.csv（TidyData形式CSV　xBRL-CSV）を検索専用ブラウザ用のCSVに変換し、ブラウザで表示する。

.horizontal_ledger.py & general_ledger.py
// [mermaid]
// ----
// classDiagram
//     class XBRLGL{XBRL}
//     class Invoice2csv{javaプログラム}

//     class instances{TidyDataCSV_xBRL-CSV}

//     class horizontal_ledger{pythonプログラム}
//     class general_ledger{pythonプログラム}

//     class horizontal_ledgerCSV{TidyDataCSV_xBRL-CSV}
//     class TrialBalance {共通CSV}
//     class GeneralLedger {共通CSV}

//     XBRLGL --|> Invoice2csv
//     Invoice2csv --|> instances

//     instances --|> horizontal_ledger
//     horizontal_ledger --|> horizontal_ledgerCSV

//     horizontal_ledgerCSV --|> general_ledger
//     general_ledger --|> TrialBalance
//     general_ledger --|> GeneralLedger
// ----
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAQoRTkI-7TzWIqkUS9swry89MTjVKLi6rzkosS3zcPP1x89rHTRseN6983LyglgtJbWZecUliXnJqcXVIZkqlS2JJonNwWHwF0ERdIANFaUZ-UWZVfl5JYk58TmpKempRdUFlSUZ-HobxCC3pqXmpRQTV47MD6AgcLkNoCinKTMxxSswB-UOh-mnrxpcNs9CUuEMc4gM2E0UNWBEkIBV0dWvskEMPLIfEhyiABxlEL5wLkcXwAVgRhigOxUAncWHXAJSB6EENU7BiVCGIMuRAwakIJVgAhhnh-w==[horizontal_ledger.py &amp; general_ledger.py]

== 会計パッケージのCSVとTidyData形式CSVの相互変換

EPSONから提供されるCSVファイルを対象に相互変換する。

.csv2tidy.py & tidy2csv.py
// [mermaid]
// ----
// classDiagram
//     class csv2tidy {pythonプログラム}
//     class tidy2csv {pythonプログラム}

//     class 北海道産業_tidy {TidyDataCSV_xBRL-CSV}
//     class 北海道産業 {EPSON形式CSV}

//     北海道産業 --|> csv2tidy
//     csv2tidy --|> 北海道産業_tidy

//     北海道産業_tidy --|> tidy2csv
//     tidy2csv --|> 北海道産業
// ----
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAQnJxmVFJZkqlQnVBZUlGft7j5umPm9c-btrwuHnl4-YFtUhKQcqMgOpxKkVS-7Rn-rOt2182Tn4-ZfGzpWvjIVaEAEmXxJJE5-Cw-AqnIB9dIKMWty6FateAYH-_p3sXPd3TD1YKVouuSle3xg7uD4hpME-BpbC5BatJ8Qg9ML-ClcE9js04AAJWnNg=[csv2tidy.py &amp; tidy2csv.py]
