= 処理フロー

== 1. 日本版コアインボイス ゲートウェイ

.Invoice2csv.java & CSV2invoice.java
// [mermaid]
// ----
// classDiagram
//     class 日本版コアインボイス{TidyDataCSV_xBRL-CSV}

//     class Invoice2csv{javaプログラム}
//     class Csv2invoice{javaプログラム}

//     class UBLinvoice {JP-PINT}
//     class CIIinvoice {中小企業共通EDI}

//     UBLinvoice --|> Invoice2csv
//     CIIinvoice --|> Invoice2csv

//     Invoice2csv --|> 日本版コアインボイス
//     日本版コアインボイス --|> Csv2invoice

//     Csv2invoice --|> UBLinvoice
//     Csv2invoice --|> CIIinvoice
// ----
.Invoice2csv.java & CSV2invoice.java
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAwrPpS5_NWfO8s-Nx0-bHTYseNy153Lz5cfMcEKNpZ3VIZkqlS2JJonNwWHyFU5CPLpBRy4Wk3zOvLD8zOdUoubisOiuxLPFx8_THzWsfN2143LzycfOCWiSlzsVlRpkQ5diVIqkNdfKBKlWo9grQDfD0C0ExytMTLv1kx9qnG_qf7Gl8tnTt09aNLxtmubp4Qg1DMkZXt8YO2bVgeSRzMOTBCpAEICrwhxdYD34lEGOQwgJiEZIARAXC6djlEU4HALveyG4=[Invoice2csv.java &amp; CSV2invoice.java]

https://www.wuwei.space/core-japan/[日本版コアインボイス変換サービス]

== 2. 検索専用ブラウザ

XBRL-GLから変換したGL_Details.csv（TidyData形式CSV　xBRL-CSV）を検索専用ブラウザ用のCSVに変換し、ブラウザで表示する。

.horizontal_ledger.py & general_ledger.py
// [mermaid]
// ----
// classDiagram
//     class XBRLGL {XBRL}
//     class XBRL_GL2csv {javaプログラム}
//     class xBRL_GL_binding {構文バインディング}

//     class GL_Details{TidyDataCSV_xBRL-CSV}

//     class horizontal_ledger{pythonプログラム}
//     class general_ledger{pythonプログラム}

//     class horizontal_ledgerCSV{TidyDataCSV_xBRL-CSV}
//     class TrialBalance {共通CSV}
//     class GeneralLedger {共通CSV}

//     XBRLGL --|> XBRL_GL2csv
//     xBRL_GL_binding --|> XBRL_GL2csv
//     XBRL_GL2csv --|> GL_Details

//     GL_Details --|> horizontal_ledger
//     horizontal_ledger --|> horizontal_ledgerCSV

//     horizontal_ledgerCSV --|> general_ledger
//     general_ledger --|> TrialBalance
//     general_ledger --|> GeneralLedger
// ----
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAQoRTkI-7j0I1iK5FE4939zFKLi5TqM5KLEt83Dz9cfPax00bHjevfNy8AFltBURtfFJmXkpmXrpC9bPl3c-mtT9unvC4acnj5s2Pm9sfNy0GMZo21HIhaQTqcUktSczMKa4OyUypdEksSXQODosHmacLZKCozcgvyqzKzytJzInPSU1JTy2qLqgsycjPw-Ou9NS81CKC6vHZAXQEDpchNIUUZSbmOCXmJOYlpypUP23d-LJhFpoSd4hDfMBmoqgBK4LGga5ujR1yuIPl0MMWqyLkyAIrQAQsxAYEHyKP4VGwKgxRHIqBLufCrgEoA9GDGvRgxahCEGXIYYdTEUroAQA9Kgbt[horizontal_ledger.py &amp; general_ledger.py]

XBRL-GL 構文バインディング xBRL_GL_binding.csv (XBRL_GL2csv.javaで使用)

https://www.wuwei.space/core-japan/journal_entry/[検索専用ブラウザ]

== 3. 会計パッケージのCSVとTidyData形式CSVの相互変換

EPSONから提供されるCSVファイルを対象に相互変換する。

.csv2tidy.py & tidy2csv.py
// [mermaid]
// ----
// classDiagram
//     class EPSON_binding {論理モデルバインディングCSV}

//     class csv2tidy {pythonプログラム}
//     class tidy2csv {pythonプログラム}

//     class GL_Details {TidyDataCSV_xBRL-CSV}
//     class 北海道産業 {EPSON形式CSV}

//     北海道産業 --|> csv2tidy
//     EPSON_binding --|> csv2tidy
//     csv2tidy --|> GL_Details

//     GL_Details --|> tidy2csv
//     EPSON_binding --|> tidy2csv
//     tidy2csv --|> 北海道産業
// ----
image::https://kroki.io/mermaid/svg/eNpLzkksLnbJTEwvSszlUgCCZJCAgmtAsL9ffFJmXkpmXrpC9YvV055PaHvcvOhxc_vj5tWPmyc8blryuHkziNu0GMRo2uAcHFbLhWREcnGZUUlmSqVCdUFlSUZ-3uPm6Y-b1wIVPm5e-bh5QS2SUpAyI6B6nEqR1Lr7xLukliRm5hQrVIcA9bkkliQCrY6vcAry0QW7AaH2ac_0Z1u3v2yc_HzK4mdL1ypUg731dO-ip3v6Ec5FV6WrW2MHdz1YBWpoYMrDvQqWQrgQYj6Si8HyMN_iMhpFHh40YCk0pwIA8pi3TA==[csv2tidy.py &amp; tidy2csv.py]

論理モデルバインディング EPSON_binding.csv

[cols="^1,4,^1,^3,^1,12,^1",%header,format=csv]
|===
column,name,card,Representation,semSort,semPath,fixedValue
-,seq,,Identifier,1010,GL02-01,
A,月種別,,,,,0
B,種類,,,,,0
C,形式,0..1,Document Reference,1240,GL55-03,
D,作成方法,,,,,0
E,付箋,,,,,0
F,伝票日付,0..1,Date,1230,GL55-02,
G,伝票番号,0..1,Code,1020,GL02-02,
H,伝票摘要,0..1,Text,1030,GL02-03,
I,枝番,0..1,Code,1220,GL55-01,
J,借方部門,0..1,Document Reference,1490,GL02-GL55[GL55-05=借方]/GL55-GL61[GL61-01=部門]/GL60-02,
K,借方部門名,0..1,Text,1500,GL02-GL55[GL55-05=借方]/GL55-GL61[GL61-01=部門]/GL60-03,
L,借方科目,1..1,Identifier,1320,GL02-GL55[GL55-05=借方]/GL55-GL63/GL63-01,
M,借方科目名,0..1,Text,1330,GL02-GL55[GL55-05=借方]/GL55-GL63/GL63-02,
N,借方補助,0..1,Text,1390,GL02-GL55[GL55-05=借方]/GL55-GL60[GL60-01=補助科目]/GL60-02,
O,借方補助科目名,0..1,Text,1400,GL02-GL55[GL55-05=借方]/GL55-GL60[GL60-01=補助科目]/GL60-03,
P,借方金額,1..1,Monetary Amount,1350,GL02-GL55[GL55-05=借方]/GL55-GL56/GL56-01,
Q,借方消費税コード,0..1,Code,1520,GL02-GL55[GL55-05=借方]/GL55-GL68[GL68-04=消費税]/GL68-01,
R,借方消費税業種,0..1,Text,1430,GL02-GL55[GL55-05=借方]/GL55-GL60[GL60-01=業種]/GL60-02,
S,借方消費税税率,0..1,Percentage,1530,GL02-GL55[GL55-05=借方]/GL55-GL68[GL68-04=消費税]/GL68-02,
T,借方資金区分,0..1,Text,1460,GL02-GL55[GL55-05=借方]/GL55-GL60[GL60-01=資金区分]/GL60-02,
U,借方任意項目１,,,,,
V,借方任意項目２,,,,,
W,貸方部門,0..1,0,1730,GL02-GL55[GL55-05=貸方]/GL55-GL61[GL61-01=部門]/GL60-02,
X,貸方部門名,0..1,Text,1740,GL02-GL55[GL55-05=貸方]/GL55-GL61[GL61-01=部門]/GL60-03,
Y,貸方科目,1..1,Identifier,1560,GL02-GL55[GL55-05=貸方]/GL55-GL63/GL63-01,
Z,貸方科目名,0..1,Text,1570,GL02-GL55[GL55-05=貸方]/GL55-GL63/GL63-02,
AA,貸方補助,0..1,Text,1630,GL02-GL55[GL55-05=貸方]/GL55-GL60[GL60-01=補助科目]/GL60-02,
AB,貸方補助科目名,0..1,Text,1640,GL02-GL55[GL55-05=貸方]/GL55-GL60[GL60-01=補助科目]/GL60-03,
AC,貸方金額,1..1,Monetary Amount,1590,GL02-GL55[GL55-05=貸方]/GL55-GL56/GL56-01,
AD,貸方消費税コード,0..1,Code,1760,GL02-GL55[GL55-05=貸方]/GL55-GL68[GL68-04=消費税]/GL68-01,
AE,貸方消費税業種,0..1,Text,1670,GL02-GL55[GL55-05=貸方]/GL55-GL60[GL60-01=業種]/GL60-02,
AF,貸方消費税税率,0..1,Percentage,1770,GL02-GL55[GL55-05=貸方]/GL55-GL68[GL68-04=消費税]/GL68-02,
AG,貸方資金区分,0..1,Text,1700,GL02-GL55[GL55-05=貸方]/GL55-GL60[GL60-01=資金区分]/GL60-02,
AH,貸方任意項目１,,,,,
AI,貸方任意項目２,,,,,
AJ,摘要,0..1,Text,1250,GL55-04,
AK,期日,0..1,Date,1290,GL55-08,
AL,証番号,0..1,Code,1270,GL55-06,
AM,入力ユーザ,0..1,Identifier,1150,GL57-01,
AN,入力マシン,0..1,Document Reference,1130,GL64-04,
AO,入力アプリ,0..1,Text,1120,GL64-03,
AP,入力会社,0..1,Text,1110,GL64-02,
AQ,入力日付,0..1,Date,1160,GL57-02,
|===

XMLの場合のXPathと同様にTidy data CSVの論理モデル上の位置を指定するためにsemPathを独自に定義した。semPathを使用すると論理階層モデル上の位置を条件づけて指定できる。

== Marmaid

VS CodeのAscii DocでMermaid Markdown Syntax Highlighting機能拡張を使用。

Mermaidについては、 +
https://mermaid.js.org/syntax/classDiagram.html

== 残作業(2023-05-23)

. pass:[検索専用ブラウザに消費税項目を追加する。] 2023-05-23 済

. pass:[EPSONからのCSVを検索専用ブラウザで表示可能とする。] 2023-05-23 済

. XBRL-GLから変換したxBRL-CSVに消費税項目を固定値として定義し、検索専用ブラウザに表示する。

. XBRL-GLから変換したxBRL-CSVをEPSONのCSVに変換する。